# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    tags:
    - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
      runs-on: windows-latest # Required by DocFX
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENCE_2019_4_12F1 }}
      steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   submodules: true

      - uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          buildMethod: UnityEditor.SyncVS.SyncSolution
          targetPlatform: StandaloneWindows64
          
      - name: Install DocFX
        run: choco install -y docfx

      - name: Build
        run: docfx Documentation/docfx.json

      # Upload the generated documentation
      - name: Upload site artifact
        uses: actions/upload-artifact@v1
        with:
          name: _site
          path: _site # Must equals the 'build.dest' value on your docfx.json
